<div class="row">
    <?php if(isset($this->formulario_empresas["tcs"])): ?>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_tipo_documento');?> <span class="importante">*</span></label>
            <select class="form-control" name="tipo_documento" required="" message="Seleccione el tipo de documento" autocomplete="off">
                <option value=""><?=$this->translate('texto_seleccionar');?>...</option>
                <?php foreach ($this->formulario_empresas["civa"]["formulario"]["tipoDocumentos"] as $key => $documento): ?>
                    <option value="<?php echo $key; ?>"><?php echo $documento; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_numero_del_documento');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="numero_documento" required="" message="<?=$this->translate('mensaje_error_numero_del_documento');?>" number="true" minlength="8" maxlength="8" autocomplete="off">
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_nombres');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="nombres" required="" message="<?=$this->translate('mensaje_error_nombres');?>" autocomplete="off">
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_correo_electronico');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="correo_electronico" required="" message="<?=$this->translate('mensaje_error_correo_electronico');?>" email="true" autocomplete="off">
        </div>
    </div>
    <?php foreach ($this->formulario_empresas["civa"]["formulario"]["menu"] as $menu): ?>
        <div class="col-md-6 col-xs-12 col-form">
            <div class="form-group">
                <label class="col-form-label" data-idmenu="<?php echo $menu['idmenu']; ?>"><?php echo $menu['menu']; ?> <span class="importante">*</span></label>
                <select class="form-control" name="<?php echo strtolower($menu['menu']); ?>" required="" message="<?=$this->translate('mensaje_error_menu');?>">
                    <option value=""><?=$this->translate('texto_seleccionar');?>...</option>
                    <?php foreach ($menu['listaMenu'] as $idmenu => $listaMenu): ?>
                        <option value="<?php echo $idmenu; ?>"><?php echo $listaMenu; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endforeach; ?>
    <?php endif; ?>
</div>