<div class="row">
    <?php if(isset($this->formulario_empresas["tcs"])): ?>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_tipo_documento');?> <span class="importante">*</span></label>
            <select class="form-control" name="tipo_documento" required="" message="<?=$this->translate('mensaje_error_tipo_documento');?>" autocomplete="off">
                <option value=""><?=$this->translate('texto_seleccionar');?>...</option>
                <?php foreach ($this->formulario_empresas["tcs"]["formulario"]["tipoDocumentos"] as $key => $documento): ?>
                    <option value="<?php echo $key; ?>"><?php echo $documento; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_numero_del_documento');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="numero_documento" required="" message="<?=$this->translate('mensaje_error_numero_del_documento');?>" number="true" minlength="8" maxlength="8" autocomplete="off">
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_apellido_paterno');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="apellido_paterno" required="" message="<?=$this->translate('mensaje_error_apellido_paterno');?>" autocomplete="off">
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_apellido_materno');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="apellido_materno" required="" message="<?=$this->translate('mensaje_error_apellido_materno');?>" autocomplete="off">
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_nombres');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="nombres" required="" message="<?=$this->translate('mensaje_error_nombres');?>" autocomplete="off">
        </div>
    </div>
    <div class="col-md-6 col-xs-12">
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <label class="col-form-label"><?=$this->translate('texto_fecha_de_nacimiento');?> <span class="importante">*</span></label>
            </div>
            <div class="col-md-4 col-xs-12 col-form">
                <div class="form-group">
                    <label class="col-form-label hidden"><?=$this->translate('texto_dia');?> <span class="importante">*</span></label>
                    <select class="form-control" name="fecha_nacimiento_dia" required="" message="<?=$this->translate('mensaje_error_dia');?>">
                        <option value=""><?=$this->translate('texto_dia');?></option>
                        <?php for($i=1;$i<=31;$i++): ?>
                        <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php endfor; ?>
                    </select>
                </div>
            </div>
            <div class="col-md-4 col-xs-12 col-form">
                <div class="form-group">
                    <label class="col-form-label hidden"><?=$this->translate('texto_mes');?> <span class="importante">*</span></label>
                    <select class="form-control" name="fecha_nacimiento_mes" required="" message="<?=$this->translate('mensaje_error_mes');?>">
                        <option value=""><?=$this->translate('texto_mes');?></option>
                        <option value="1">Enero</option>
                        <option value="02">Debrero</option>
                        <option value="03">marzo</option>
                        <option value="04">Abril</option>
                        <option value="05">Mayo</option>
                        <option value="06">Junio</option>
                        <option value="07">Julio</option>
                        <option value="08">Agosto</option>
                        <option value="09">Septiembre</option>
                        <option value="10">Octubre</option>
                        <option value="11">Noviembre</option>
                        <option value="12">Diciembre</option>
                    </select>
                </div>
            </div>
            <div class="col-md-4 col-xs-12 col-form">
                <div class="form-group">
                    <label class="col-form-label hidden"><?=$this->translate('texto_ano');?> <span class="importante">*</span></label>
                    <select class="form-control" name="fecha_nacimiento_ano" required="" message="<?=$this->translate('mensaje_error_ano');?>">
                        <option value=""><?=$this->translate('texto_ano');?></option>
                        <?php for($i=date('Y');$i>=1905;$i--): ?>
                        <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php endfor; ?>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_nacionalidad');?> <span class="importante">*</span></label>
            <select class="form-control" data="nacionalidad" name="nacionalidad" required="" message="<?=$this->translate('mensaje_error_nacionalidad');?>">
                <option value=""><?=$this->translate('texto_seleccionar');?>...</option>
                <?php foreach ($this->formulario_empresas["tcs"]["formulario"]["nacionalidades"] as $key => $nacionalidad): ?>
                    <option value="<?php echo $key; ?>"><?php echo $nacionalidad; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form" style="display: none;">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_departamento');?> <span class="importante">*</span></label>
            <select class="form-control" data="departamentos" name="departamento" message="<?=$this->translate('mensaje_error_departamento');?>">
                <option value=""><?=$this->translate('texto_seleccionar');?>...</option>
                <?php foreach ($this->formulario_empresas["tcs"]["formulario"]["departamentos"] as $key => $departamento): ?>
                    <option value="<?php echo $key; ?>"><?php echo $departamento; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form" style="display: none;">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_distrito');?>Distrito <span class="importante">*</span></label>
            <select class="form-control" data="distritos" name="distrito" message="<?=$this->translate('mensaje_error_distrito');?>"></select>
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_telefono_de_contacto');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="telefono_contacto" required="" message="<?=$this->translate('mensaje_error_telefono_de_contacto');?>" number="true" autocomplete="off">
        </div>
    </div>
    <div class="col-md-6 col-xs-12 col-form">
        <div class="form-group">
            <label class="col-form-label"><?=$this->translate('texto_correo_electronico');?> <span class="importante">*</span></label>
            <input type="text" class="form-control" name="correo_electronico" required="" message="<?=$this->translate('mensaje_error_correo_electronico');?>" email="true" autocomplete="off">
        </div>
    </div>
    <?php foreach ($this->formulario_empresas["tcs"]["formulario"]["menu"] as $menu): ?>
        <div class="col-md-6 col-xs-12 col-form">
            <div class="form-group">
                <label class="col-form-label" data-idmenu="<?php echo $menu['idmenu']; ?>"><?php echo ($this->translate('extension_idioma') != 'es')?$this->idioma_lista_menu[trim($menu['menu'])][$this->translate('extension_idioma')]:$menu['menu']; ?> <span class="importante">*</span></label>
                <select class="form-control" name="<?php echo strtolower($menu['menu']); ?>" required="" message="<?=$this->translate('mensaje_error_menu');?>">
                    <option value=""><?=$this->translate('texto_seleccionar');?>...</option>
                    <?php foreach ($menu['listaMenu'] as $idmenu => $listaMenu): ?>
                        <option value="<?php echo $idmenu; ?>"><?php echo $listaMenu; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endforeach; ?>
    <?php endif; ?>
</div>