<?= $this->doctype() ?>
<html lang="es">
    <head>
        <base href="/">
        <meta charset="UTF-8">
        <title>EBUS - Búsqueda</title>
        <link rel="shortcut icon" href="img/icon.png">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="robots" content="all,follow">
        <link rel="stylesheet" href="css/bootstrap.css">
        <link rel="stylesheet" href="css/fontawesome.min.css">
        <link rel="stylesheet" href="css/style.css">
    </head>
    <style>
        header{
            width: 100%;
            height: auto;
            padding: 14px;
        }
        footer{
            width: 100%;
            height: 40px;
        }
        .center{
            text-align: center;
        }
    </style>
    <body>
        <header>
            <h2 class="center">Golosinas Chelita</h2>
        </header>
        <main>
        <?= $this->content ?>
        </main>
        <footer></footer>
        <script src="js/jquery.js"></script>
        <script src="js/bootstrap.js"></script>
        <script src="js/validate/jquery.validate.min.js"></script>
        <script src="js/validate/localization/messages_es.js"></script>
        <?= $this->inlineScript() ?>
    </body>
</html>