<?= $this->doctype() ?>
<html lang="es">
    <head>
        <base href="/">
        <meta charset="UTF-8">
        <title>EBUS - Búsqueda</title>
        <link rel="shortcut icon" href="img/icon.png">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="robots" content="all,follow">
    </head>
    <body>
        <?= $this->content ?>
    </body>
</html>