<style>
	form section,
	form input{
		width: 100%;
	}
	form section{
		margin-bottom: 5px;
	}
	form input,
	form textarea{
		border-radius: 0px!important;
		font-size: 16px!important;
		color: #b1b1b1!important;
	}
</style>
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-xs-12">
				<form action="">
					<section class="form-group">
						<label>Producto</label>
						<input type="text" class="form-control" placeholder="Ingrese el nombre del producto" value="Morochas">
					</section>
					<section class="form-group">
						<label>Descripción</label>
						<textarea class="form-control" placeholder="Ingrese el nombre del producto">Galletas Morochas Bolsa 46 g</textarea>
					</section>
					<section class="form-group">
						<label>Precio Caja</label>
						<input type="text" class="form-control" placeholder="Ingrese el nombre del producto" value="14.00">
					</section>
					<section class="form-group">
						<label>Precio Caja Comerciantes</label>
						<input type="text" class="form-control" placeholder="Ingrese el nombre del producto" value="13.50">
					</section>
					<section class="form-group">
						<label>Precio Unidad</label>
						<input type="text" class="form-control" placeholder="Ingrese el nombre del producto" value="1.60">
					</section>
				</form>
			</div>
		</div>
	</div>
</section>